# Use Go image
FROM golang:1.23.0

# Install necessary packages including MySQL client and specific PostgreSQL client version
RUN apt-get update && \
    apt-get install -y wget gnupg default-mysql-client && \
    echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y postgresql-client-16 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Setup application
WORKDIR /app
RUN go install github.com/air-verse/air@latest
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main .

# Expose port and define entrypoint
EXPOSE 8080
CMD ["air"]
