name: Dev Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      safebase_db:
        image: postgres:16
        ports:
          - 5434:5432
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd "pg_isready -U $DB_USER"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - ${{ github.workspace }}/sql/safebase_db/safebase.sql:/docker-entrypoint-initdb.d/safebase.sql

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check SQL file existence and permissions
        run: |
          if [ ! -f ./sql/safebase_db/safebase.sql ]; then
            echo "Error: safebase.sql does not exist."
            exit 1
          fi
          chmod 644 ./sql/safebase_db/safebase.sql
          file ./sql/safebase_db/safebase.sql

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./backend

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5434; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      - name: Run tests
        env:
          DATABASE_URL: postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost:5434/${{ secrets.DB_NAME }}?sslmode=disable
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: localhost
          DB_PORT: 5434
        run: |
          cd backend
          go test ./...
